config/routes.rb
Rails.application.routes.draw do
  root "posts#index"
  

  get "homes/about" => "homes#about"
  get "homes/privacy" => "homes#privacy"

  devise_for :users, controllers: {
    sessions: "devise/sessions",
    registrations: "devise/registrations",
  }

  post 'posts/confirm' => 'posts#confirm'
  resources :posts, only: [:index, :new, :create, :edit, :update, :show, :destroy] do
    resource :likes, only: [:create, :destroy]
    resource :post_comments, only: [:create]
  end
  delete "posts/:post_id/post_comments/:post_comment_id", to: "post_comments#destroy", as: :post_comment
  post "posts/:post_id/post_comments/:post_comment_id/thanks", to: "thanks#create", as: :thank
  delete "posts/:post_id/post_comments/:post_comment_id/thanks", to: "thanks#destroy"

  resource :tags, only: [:create, :destroy]
  resources :users, only: [:show, :edit, :update] do
    member do
      get :follow
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  post "/home/guest_sign_in" => "posts#new_guest"
  resources :relationships, only: [:create, :destroy]
  resources :stocks, only: [:index, :create, :destroy]

  # #例外処理
  # get '*not_found', to: 'application#routing_error'
  # post '*not_found', to: 'application#routing_error'
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :post
  belongs_to :user
  has_many :thanks, dependent: :destroy

  def thanked_by?(user)
    thanks.where(user_id: user.id).exists?
  end
end

app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController
  before_action :set_post_comment

  def create
    comment = PostComment.new(post_comment_params)
    comment.user_id = current_user.id
    comment.post_id = @post.id
    comment.save
  end

  def destroy
    comment = PostComment.find(params[:post_comment_id])
    comment.destroy
  end

  private

  def set_post_comment
    @post = Post.find(params[:post_id])
  end

  def post_comment_params
    params.require(:post_comment).permit(:text)
  end
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/views/post_comments/_form.html.erb
<div class="post-comment-form">
	<% if user_signed_in? %>
		<div>
		    <%= form_with(model:[post,post_comment], url:post_post_comments_path(post)) do |f| %>
				<!-- current_userがその投稿に気になるをしていたら -->
				<% ids = post.likes.pluck('user_id') %>
				<% if ids.size > (ids - [current_user.id]).size %>
					<%= f.text_area :text, class: "comment-form form-control" %>
					<%= f.submit "コメントする", class: "post-comment-submit" %>
				<% end %>
			<% end %>
		</div>
	<% else %>
		<div class="before-login-topic">ログインするとコメント出来ます</div>
			<button class="before-login"><%= link_to  "ログインする", new_user_session_path, class: 'before-login-btn' %></button>
	<% end %>
</div>

app/views/post_comments/_postcomment.html.erb
<% if post.post_comments.exists? %>
	<% post.post_comments.each do |post_comment| %>
		<div class="comment-whole">
			<div class="comment-top">
				<%= link_to user_path(post_comment.user) do %>
					<%= attachment_image_tag post_comment.user, :profile_image, :fill, 50, 50,fallback: "no_image.jpg", class: 'image' %>
				<% end %>
				<span style="margin-top: 10px;"><%= link_to post_comment.user.name, user_path(post_comment.user) %></span>
				<span class="pull-right"><%= post_comment.created_at.to_s(:datetime) %></span>
			</div>
			<div class="comment-main">
				<%= safe_join(post_comment.text.split("\n"),tag(:br)) %>
				<% if post_comment.user == current_user %>
					<span class="comment-delete pull-right">
						<%= link_to '削除',post_comment_path(post_comment.post,post_comment), method: :delete, remote: true, data: {confirm: "本当に消しますか" } %>
					</span>
				<% end %>
			</div>
			<div class="thank-area">
				<% if current_user == post.user %>
					<% if post_comment.thanked_by?(current_user) %>
					  	<%= link_to thank_path(post_comment_id: post_comment.id, post_id: post.id), method: :delete, local: true do %>
						  	<%= image_tag'7019.jpg', :size => '20x20', class: "thank-image" %>
						    ありがとうを押しました
					  	<% end %>
					<% else %>
					  	<%= link_to thank_path(post_comment_id: post_comment.id, post_id: post.id), method: :post, local: true do %>
						    <%= image_tag'7019.jpg', :size => '20x20' %>
						   	ありがとう
					  	<% end %>
					<% end %>
				<% end %>
			</div>
		</div>
	<% end %>
<% else %>
	コメントはまだありません
<% end %>

app/views/post_comments/create.js.erb
$("#post_comments_area").html("<%= j(render partial:'post_comments/postcomment', locals: {post: @post})%>");
$("textarea").val('');

app/views/post_comments/destroy.js.erb
$("#post_comments_area").html("<%= j(render partial:'post_comments/postcomment', locals: {post: @post})%>");