config/routes.rb
Rails.application.routes.draw do
  root "posts#index"
  

  get "homes/about" => "homes#about"
  get "homes/privacy" => "homes#privacy"

  devise_for :users, controllers: {
    sessions: "devise/sessions",
    registrations: "devise/registrations",
  }

  post 'posts/confirm' => 'posts#confirm'
  resources :posts, only: [:index, :new, :create, :edit, :update, :show, :destroy] do
    resource :likes, only: [:create, :destroy]
    resource :post_comments, only: [:create]
  end
  delete "posts/:post_id/post_comments/:post_comment_id", to: "post_comments#destroy", as: :post_comment
  post "posts/:post_id/post_comments/:post_comment_id/thanks", to: "thanks#create", as: :thank
  delete "posts/:post_id/post_comments/:post_comment_id/thanks", to: "thanks#destroy"

  resource :tags, only: [:create, :destroy]
  resources :users, only: [:show, :edit, :update] do
    member do
      get :follow
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  post "/home/guest_sign_in" => "posts#new_guest"
  resources :relationships, only: [:create, :destroy]
  resources :stocks, only: [:index, :create, :destroy]

  # #例外処理
  # get '*not_found', to: 'application#routing_error'
  # post '*not_found', to: 'application#routing_error'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates_uniqueness_of :post_id, scope: :user_id
end

app/models/post.rb
class Post < ApplicationRecord
  acts_as_taggable
  belongs_to :user, optional: true
  has_many :post_comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  validates :title, presence: true, length: { maximum: 20 }
  validates :text, presence: true
  validates :emoji, presence: true
  validates :tag_list, presence: true

  has_many :stocks, dependent: :destroy
  has_many :stock_users, through: :stocks, source: :user

  enum status: { doing: 0, done: 1 }

  def liked_by?(user)
    likes.where(user_id: user.id).exists?
  end

  def stock(user)
    stocks.create(user_id: user.id)
  end

  def unstock(user)
    stocks.find_by(user_id: user.id).destroy
  end

  def stocked?(user)
    stock_users.include?(user)
  end
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :post
  belongs_to :user
  has_many :thanks, dependent: :destroy

  def thanked_by?(user)
    thanks.where(user_id: user.id).exists?
  end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/stock.rb
class Stock < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :user_id, presence: true
  validates :post_id, presence: true

  def self.get_stock_posts(user)
    where(user_id: user.id).map(&:post)
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
end

app/models/thank.rb
class Thank < ApplicationRecord
  belongs_to :user
  belongs_to :post_comment
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :thanks, dependent: :destroy

  attachment :profile_image

  validates :name, presence: true, length: { minimum: 2, maximum: 20 }
  validates :introduction, presence: true, length: { maximum: 500 }

  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed

  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :passive_relationships, source: :follower

  has_many :stocks, dependent: :destroy

  def follow(other_user)
    following << other_user
  end

  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end

  def privacy
  end
  
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_post

  def create
    like = @post.likes.new(user_id: current_user.id)
    like.save
    redirect_to request.referrer
  end

  def destroy
    like = current_user.likes.find_by(post_id: @post.id)
    like.destroy
    redirect_to request.referrer
  end

  private

  def set_post
    @post = Post.find(params[:post_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    @post = params[:post].present? ? Post.new(post_params) : Post.new
    @post.tag_list = params[:post].present? ? params[:post][:tag_list].split(',') : ""
    @post.emoji = params[:post].present? ? params[:post][:emoji] : "😄"
    @user = current_user
  end

  def confirm
    @post = Post.new(post_params)
  end

  def create
    @post = Post.new(post_params)
    @post.tag_list = params[:post][:tag_list]
    if @post.save
      flash[:notice] = "投稿が完了しました"
      redirect_to user_path(current_user)
    else
      render 'confirm'
    end
  end

  def index
    @all_ranking_posts = Post.find(Like.group(:post_id).order('count(post_id) desc').limit(10).pluck(:post_id))
    @contributors = PostComment.find(PostComment.group(:user_id).order('count(id) desc').limit(5).pluck(:id))

    @tags = Post.tag_counts_on(:tags).order('count desc')

    @q = Post.ransack(params[:q])
    if params[:tag_name]
      @posts = Post.tagged_with("#{params[:tag_name]}").includes(:tags).order(created_at: :desc).page(params[:page]).per(10)
    elsif params[:q]
      @posts = @q.result.order(created_at: :desc).page(params[:page]).per(10)
    else
      @posts = Post.all.order(created_at: :desc).page(params[:page]).per(10)
    end
    @user = current_user
  end

  def show
    @post = Post.find(params[:id])
    @post_comment = PostComment.new
    @post_comments = @post.post_comments.order(created_at: :desc)
  end

  def edit
    @post = Post.find(params[:id])
    if @post.user == current_user
      render 'edit'
    else
      redirect_back(fallback_location: posts_path, notice: "URLが有効ではありません")
    end
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      flash[:notice] = "更新しました"
      redirect_to post_path
    else
      render :edit
    end
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    flash[:notice] = "削除しました"
    redirect_to user_path(current_user)
  end

  def new_guest
    user = User.find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = 'guest'
      user.introduction = 'ゲストです。よろしくお願いします。'
    end
    sign_in user
    flash[:notice] = 'ゲストユーザーとしてログインしました。'
    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:user_id, :title, :text, :tag_list, :status, :emoji)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @posts = @user.posts.order(created_at: :desc)
    @comments = @user.post_comments.order(created_at: :desc)
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render 'edit'
    else
      redirect_back(fallback_location: user_path(current_user), notice: "URLが有効ではありません")
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "更新しました"
      redirect_to user_path
    else
      render 'edit'
    end
  end

  def follow
    @user = User.find(params[:id])
    @followers_users = User.find(params[:id]).followers
    @following_users = User.find(params[:id]).following
  end

  private

  def user_params
    params.require(:user).permit(:email, :name, :introduction, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/thanks_helper.rb
module ThanksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/likes/_like.html.erb
<% if post.liked_by?(current_user) %>
  <%= link_to post_likes_path(post), method: :delete, remote: true do %>
    <i class="fa fa-heart index-like" style="color: red;" aria-hidden="true", id="liking-btn"></i>
  <% end %>
<% else %>
  <%= link_to post_likes_path(post), method: :post, remote: true do %>
    <i class="far fa-heart index-like" aria-hidden="true", id="nolike-btn"></i>
  <% end %>
<% end %>

app/views/likes/create.js.erb
$('#likes_buttons_<%= @post.id %>').html("<%= j(render partial: 'likes/like', locals: {post: @post}) %>");

app/views/posts/index.html.erb
<% unless user_signed_in? %>
	<div class="topper">
		<div class="container">
			<div class="row">		
				<div class="login-header">
					<div class="notification">
						<%= flash[:notice] %>
					</div>
					<div class="top-left col-lg-6 col-md-6">
						<h1 class="top-slogan"><strong>Ask for advice.</strong></h1>
						<p class="top-subject">ノットウォーリーは20代のキャリアの悩みを解決するサイトです</p>
						<div class="top-btn">
							<span class="top-guestlogin"><%= link_to "ゲストログイン（閲覧用）", home_guest_sign_in_path, method: :post, class: 'btn btn-success' %></span>
							<span class="top-about"><%= link_to "About notworry", homes_about_path, class: "btn btn-warning" %></span>
						</div>
					</div>
					<div class="top-right col-lg-6 col-md-6">
						<%= image_tag'Devices-bro.png', class: 'login-image' %>
					</div>
				</div>
			</div>
		</div>
	</div>
<% end %>

<div class="search-window container">
	<div class="row search-row">
		<% if user_signed_in? %>
			<div class="notification-login">
					<%= flash[:notice] %>
			</div>
		<% end %>
		<%= search_form_for @q do |f| %>
			<span class="fa fa-search">
	  			<%= f.search_field :text_cont, placeholder: "本文検索", class: "search-input" %>
	  		</span>
		<% end %>
	</div>
	<div class="gretel">
		<% if params[:q] %>
			<% breadcrumb :postsq, @posts %>
			<%= breadcrumbs separator: " &rsaquo; " %>
		<% elsif params[:tag_name] %>
			<% breadcrumb :tag, @posts %>
			<%= breadcrumbs separator: " &rsaquo; " %>
		<% else %>
			<% breadcrumb :posts, @posts %>
			<%= breadcrumbs separator: " &rsaquo; " %>
		<% end %>
	</div>
</div>
	
<div class="container post-index-container">
	<div class="row">
		<div class="tab col-md-7">
		    <ul class="menu">
		      <li class="tab-list1"><%= link_to '相談一覧', '#', class: 'active', data: {id: "main"} %></li>
		      <li class="tab-list2"><%= link_to '注目の投稿', '#', data: {id: "attention"} %></li>
		      <li class="tab-list3"><%= link_to '解決済', '#', data: {id: "solved"} %></li>
		      <li class="tab-list4"><%= link_to '人気タグ', '#', data: {id: "popularity"} %></li>
		    </ul>
	    	<section class='content active' id="main">
	    		<% if @q.result.present? %>
					<% @posts.each do |post| %>
						<div class="post-middle row">
							<div class="post-middle-inner">
								<div class="emoji col-md-5 col-sm-5 col-xs-5">
									<div class="emoji-inner col-md-7 col-sm-7 col-xs-7">
										<%= post.emoji %>
									</div>
								</div>
								
								<div class="post-index col-md-7 col-sm-7 col-xs-7">
									<div class="post-article">
										
										<span class="index-title"><%= link_to post.title, post_path(post) %></span>	
									</div>
									<div class="post-ul">
										<span>
											<%= link_to user_path(post.user) do %>
												<%= attachment_image_tag post.user, :profile_image, :fill, 20, 20,fallback: "no_image.jpg", class: 'post-image' %>
											<% end %>
										</span>
										
									</div>
									<span>
										<%= link_to post.user.name, user_path(post.user) %>
									</span>
									<!-- 気になるボタン -->
									<div>
										<% if user_signed_in? %>
											<% if current_user != post.user %>
												<i class="far fa-heart index-like" aria-hidden="true", id="nolike-btn"></i>
												<span class="likes-count">
													<%= post.likes.count %>
												</span>
											<% end %>
										<% end %>
									</div>
									<!-- 気になるボタン -->
								</div>
							</div>
							
						</div>
					<% end %>
				<% else %>
					<div class="search-result">
						<%= @q.text_cont %>　に関連する記事はありませんでした。
					</div>
				<% end %>
				<%= paginate @posts %>
			</section>
			<section class="content" id="attention">
	      		<div class="posts-ranking">
					<% @all_ranking_posts.each do |post| %>
						<div class="rank-posts">
							
							<span class="attention-title"><%= link_to post.title, post_path(post) %></span>
							
							<div class="rank-contents">
								<span>
									<%= attachment_image_tag post.user, :profile_image, :fill,20, 20,fallback: "no_image.jpg", class: 'post-image' %>
								</span>
								<span class="rank-content"><%= time_ago_in_words(post.created_at) %>前に投稿</span>
								<span class="attention-count pull-right"><%= post.likes.count %>人が注目</span>
							</div>
						</div>
					<% end %>
				</div>
	    	</section>
	    	<section class="content" id="solved">
				<% if @q.result.present? %>
					<% @posts.each do |post| %>
						<% if post.status == "done" %>
							<div class="post-middle row">
								<div class="post-middle-inner">
									<div class="comment-counts col-sm-2 col-xs-3">
										<div class="post-middle-left row">
											<div class="<%= post.status %> post-status"><%= post.status_i18n %></div>
											<div class="post-comments-count">
												<p class="post-response">回答</p>
												<h4><%= post.post_comments.count %></h4>
											</div>
										</div>
									</div>
									<div class="post-index col-sm-8 col-xs-6">
									<div class="post-article">
										
										<span class="index-title"><%= link_to post.title, post_path(post) %></span>	
									</div>
									<div class="post-ul">
										<span>
										<%= link_to user_path(post.user) do %>
											<%= attachment_image_tag post.user, :profile_image, :fill, 20, 20,fallback: "no_image.jpg", class: 'post-image' %>
										<% end %>
										</span>
										
									</div>
									<span>
										<%= link_to post.user.name, user_path(post.user) %>
									</span>
									<!-- 気になるボタン -->
									<div>
										<% if user_signed_in? %>
											<% if current_user != post.user %>
												<i class="far fa-heart index-like" aria-hidden="true", id="nolike-btn"></i>
												<span class="likes-count">
													<%= post.likes.count %>
												</span>
											<% end %>
										<% end %>
									</div>
									<!-- 気になるボタン -->
								</div>
								</div>
							</div>
						<% end %>
					<% end %>
				<% else %>
					<div class="search-result">
						関連する記事はありません。
					</div>
				<% end %>
		    </section>
		    <section class="content" id="popularity">
		    	<div class="population-tag">
					<% @tags.each do |tag| %>
						<button class="post-button tab-bar">
							#<%= link_to tag.name, posts_path(tag_name: tag.name), class: "tag-btn tab-bar-tag" %>
						</button>
					<% end %>
				</div>
		    </section>
		</div>
		<div class="user-info col-md-5">
			<% if user_signed_in? %>
				<div class="index-details">
					<div class="index-details-inner">
						<div class="inner-more">
							<div class="index-detail-head">
								<div class="detail-head-topic">
									<span><%= attachment_image_tag current_user, :profile_image, :fill,20, 20, format: 'jpeg', fallback: "no_image.jpg", class: 'detail-head-image' %></span>
									<span class="profile-name"><%= current_user.name %></span>
								</div>
							</div>
							<div class="index-detail-foot row">
								<div class="index-detail-left col-md-4">
									<p class="index-detail"><%= link_to @user.posts.count, user_path(@user) %></p>
									<p class="index-detail-letter"><%= link_to '投稿', user_path(@user) %></p>
									
								</div>
								<div class="index-detail-middle col-md-4">
									<p class="index-detail"><%= link_to @user.following.count, follow_user_path(@user) %></p>
									<p class="index-detail-letter"><%= link_to 'フォロー', follow_user_path(@user) %></p>
								</div>
								<div class="index-detail-right col-md-4">
									<p class="index-detail"><%= link_to @user.followers.count, follow_user_path(@user) %></p>
									<p class="index-detail-letter"><%= link_to 'フォロワー', follow_user_path(@user) %></p>
								</div>
							</div>
						</div>
					</div>
				</div>
			<% end %>
			<div class="comment-rank">
				<div class="comment-rank-inner">
					<div class="rank-inner-more">
						<h4 class="comment-letter">コメント貢献者ランキング</h4>
						<% @contributors.each.with_index(1) do |contributor,i| %>
							<div class="rank-comments">
								<div class="rank-left">
									<% if i == 1 %>
										<span class="ranking">
											<i class="fas fa-trophy is-gold"></i>
										</span>
									<% elsif i == 2 %>
										<span class="ranking">
											<i class="fas fa-trophy is-silver"></i>
										</span>
									<% elsif i == 3 %>
										<span class="ranking">
											<i class="fas fa-trophy is-blonze"></i>
										</span>
									<% else %>
										<span class="ranking other">
											<%= i %>
										</span>
									<% end %>
									<span>
										<%= attachment_image_tag contributor.user, :profile_image, :fill,20, 20,fallback: "no_image.jpg", class: 'post-image' %>
									</span>
									<span class="ranking-title"><%= link_to contributor.user.name, user_path(contributor.user) %></span>
									<% if user_signed_in? %>
									<span class="index-follow pull-right">
										<% if contributor.user == current_user %>
											<span class="rank-in"><%= '🎉' %></span>
										<% elsif current_user.following.include?(contributor.user) %>
											<%= render 'users/unfollow', user: contributor.user %>
										<% else %>
											<%= render 'users/follow', user: contributor.user %>
										<% end %>
									</span>
									<% end %>
								</div>
							</div>
						<% end %>
					</div>
				</div>
			</div>
		</div>
		
	</div>
</div>

<div class="container app-link-container">
	<div class="row app-link-row">

			<%= image_tag'app_store_logo-43fe606e0484142c0df690530c3e925c4cdafb9ee80a7cf13a322803d446d2c8.png', class: "apple-image col-sm-6" %>
			<%= image_tag'google-play-badge-a68cd60e8b6b59e46035419afd6c3dba79b03859b7e651d64a960b55a5e1e583.png', :size => '248x82', style: "border-radius: 13px", class: "google-image col-sm-6" %>
			<div class="app-coming col-sm-12"><strong>Coming Soon ...</strong></div>

		
	</div>
</div>

app/views/posts/show.html.erb
<div class="container post-show-container">
	<div class="row">
		<div class="gretel">
			<% breadcrumb :post, @post %>
			<%= breadcrumbs separator: " &rsaquo; " %>
		</div>
		<div class="show-notice">
			<%= flash[:notice] %>
		</div>

			<div class="stock-icon">
				<!-- 自身の投稿以外 かつ ログインしているユーザーであれば -->
				<% if current_user != @post.user && user_signed_in? %>
						<!-- 既にストックしている記事であれば「ストック解除ボタン」を表示 -->
						<% if @post.stocked?(current_user) %>
						<!-- stocksコントローラーのdestoryアクションにmethod: :deleteで指定して送信 -->
						<%= form_with model: @post.stocks.find_by(user_id: current_user.id), method: :delete do |f| %>
							<%= f.button(class: "btn btn-dark") do %>
							<i class="fas fa-folder fa-lg"></i> ストック中
							<% end %>
						<% end %>
						<!-- ストックしていない記事であれば「ストックボタン」を表示 -->
						<% else %>
							<!-- buildでstocksコントローラーのcreateアクションへ -->
							<%= form_with model: @post.stocks.build, url: stocks_path(post_id: @post.id) do |f| %>
								<%= f.button(class: "btn btn-outline-dark") do %>
									<i class="far fa-folder fa-lg"></i> ストックする
								<% end %>
							<% end %>
						<% end %>
				<% end %>
			</div>
			<div>
				<div class="show-emoji">
					<%= @post.emoji %>
				</div>
				<div class="show">
					<div class="post-created text-right"><%= @post.created_at.to_s(:datetime) %></div>
					<div class="show-top">
						<%= link_to user_path(@post.user) do %>
							<span>
								<%= attachment_image_tag @post.user, :profile_image, :fill, 50, 50,fallback: "no_image.jpg", class: 'image' %>
							</span>
						<% end %>
						<span class="show-title"><%= link_to @post.user.name, user_path(@post.user) %></span>
						<% if current_user == @post.user %>
							<span class="post-destroy pull-right">
								<%= link_to post_path(@post), method: :delete, data: {confirm: "本当に消しますか" } do %>
									<i class="far fa-trash-alt">削除する</i>
								<% end %>
							</span>
						<% end %>
						<% if current_user == @post.user %>
							<span class="post-edit pull-right">
								<%= link_to edit_post_path(@post) do %>
									<i class="far fa-edit">編集する</i>
								<% end %>
							</span>
						<% end %>
						<!-- 気になるボタン -->
						<% if user_signed_in? %>
							<% if current_user != @post.user %>
								<span class="pull-right post-like", id="likes_buttons_<%= @post.id %>">
									<%= render 'likes/like', post: @post %>
								</span>
							<% end %>
						<% end %>
						<!-- 気になるボタン -->
					</div>
					<h2><strong><%= @post.title %></strong></h2>
					<% @post.tags.each do |tag| %>
						<span class="post-tag">
							<button class="show-span-tag"><%= link_to tag.name, posts_path(tag_name: tag.name), class: "tag-btn" %></button>
						</span>
					<% end %>
					<p class="posts-show-text"><%= safe_join(@post.text.split("\n"),tag(:br)) %></p>
				</div>
				<div class="comment-bottom">
					<i class="fas fa-comments"></i>
					<span>コメント
						<% if @post.user != current_user && user_signed_in? %>
							<span>( <i class="far fa-heart index-like" aria-hidden="true", id="nolike-btn"></i> を押す事でコメントが出来るようになります）</span>
						<% elsif @post.user != current_user || user_signed_in? %>
						<% end %>
					</span>
					<div class="comment-field">
						<div class="comment-area", id="post_comments_area">
							<%= render partial: 'post_comments/postcomment', locals: { post: @post } %>
						</div>
					</div>
				</div>
				<div class="comment-form text-center center-block">
					<% if current_user != @post.user%>
						<span class="show-like", id="likes_buttons_<%= @post.id %>">
							<%= render partial: 'post_comments/form', locals: { post_comment: @post_comment, post: @post }  %>
						</span>
					<% end %>
				</div>
			</div>

	</div>
</div>

app/views/users/show.html.erb
<div class="container user-show-container">
	<div class="row">
		<div class="gretel">
			<% breadcrumb :user, @user %>
			<%= breadcrumbs separator: " &rsaquo; " %>
		</div>
		<div class="user-message">
			<%= flash[:notice] %>
		</div>
	</div>
	<div class="row">
		<div class="user-show-right col-md-3">
			<h3><strong>ユーザー情報</strong></h3>
			<div class="show-name"> 
				<h4>名前</h4>
				<p class="show-name-topic"><%= @user.name %></p><br>
			</div>
			<div class="show-introduction">
				<h4>経歴</h4>
				<p class="show-introduction-topic"><%= @user.introduction %></p><br>
			</div>
			<div class="user-show-edit">
				<% if user_signed_in? %> 
				<% if @user == current_user %>
			      	<%= link_to "プロフィールを編集する", edit_user_path(@user), class: 'btn btn-profile' %>
			    <% else %>
			    	<% if current_user.following.include?(@user) %>
				        <%= render 'users/unfollow', user: @user %>
				    <% else %>
				    	<%= render 'users/follow', user: @user %>
				    <% end %>
				<% end %>
				<% end %>
			</div>
		</div>
		<div class="user-show-middle col-md-5">
			<div class="show-right-top">
				<h3><strong>すべての投稿</strong></h3>
				<% if @posts.exists? %>
					<% @posts.each do |post| %>
						<div class="article-column">
							<h4><strong><%= link_to post.title, post_path(post) %></strong></h4>投稿日時: <%= post.created_at.to_s(:datetime) %>
							<h4 class="column-title"><%= "#{post.likes.count} 人が注目してます" %></h4>
						</div>
					<% end %>
				<% else %>
					<p>投稿はまだありません</p>
				<% end %>
			</div>
			<div class="show-right-bottom">
				<h3><strong>すべてのコメント</strong></h3>
				<% if @comments.exists? %>
					<% @comments.each do |comment| %>
						<div class="column-title">
							<h4><strong><%= link_to comment.text.truncate(50), post_path(comment.post) %></strong></h4>
							<p>投稿日時:  <%= comment.created_at.to_s(:datetime) %></p>
							<p><%= link_to comment.post.user.name, user_path(comment.post.user) %>さんへのコメント</p>
						</div>
					<% end %>
				<% else %>
					<p>コメントはまだありません</p>
				<% end %>
			</div>
		</div>
		<div class="show-details col-md-4">
			<div class="show-inner-more">
				<div class="show-detail-head">
					<div class="show-head-topic">
						<%= attachment_image_tag @user, :profile_image, :fill,20, 20,fallback: "no_image.jpg", class: 'detail-head-image' %>
					</div>
				</div>
				<div class="show-detail-foot row">
					<div class="show-detail-left col-md-4">
						<p class="show-detail"><%= link_to @user.posts.count, user_path(@user) %></p>
						<p class="show-detail-letter"><%= link_to '投稿', user_path(@user) %></p>
					</div>
					<div class="show-detail-middle col-md-4">
						<p class="show-detail"><%= link_to @user.following.count, follow_user_path(@user) %></p>
						<p class="show-detail-letter"><%= link_to 'フォロー', follow_user_path(@user) %></p>
					</div>
					<div class="show-detail-right col-md-4">
						<p class="show-detail"><%= link_to @user.followers.count, follow_user_path(@user) %></p>
						<p class="show-detail-letter"><%= link_to 'フォロワー', follow_user_path(@user) %></p>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>