config/routes.rb
Rails.application.routes.draw do
  root "posts#index"
  

  get "homes/about" => "homes#about"
  get "homes/privacy" => "homes#privacy"

  devise_for :users, controllers: {
    sessions: "devise/sessions",
    registrations: "devise/registrations",
  }

  post 'posts/confirm' => 'posts#confirm'
  resources :posts, only: [:index, :new, :create, :edit, :update, :show, :destroy] do
    resource :likes, only: [:create, :destroy]
    resource :post_comments, only: [:create]
  end
  delete "posts/:post_id/post_comments/:post_comment_id", to: "post_comments#destroy", as: :post_comment
  post "posts/:post_id/post_comments/:post_comment_id/thanks", to: "thanks#create", as: :thank
  delete "posts/:post_id/post_comments/:post_comment_id/thanks", to: "thanks#destroy"

  resource :tags, only: [:create, :destroy]
  resources :users, only: [:show, :edit, :update] do
    member do
      get :follow
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  post "/home/guest_sign_in" => "posts#new_guest"
  resources :relationships, only: [:create, :destroy]
  resources :stocks, only: [:index, :create, :destroy]

  # #例外処理
  # get '*not_found', to: 'application#routing_error'
  # post '*not_found', to: 'application#routing_error'
end

app/models/stock.rb
class Stock < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :user_id, presence: true
  validates :post_id, presence: true

  def self.get_stock_posts(user)
    where(user_id: user.id).map(&:post)
  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  def index
    # ログインユーザーがストックした記事一覧を取得
    @stock_posts = Stock.get_stock_posts(current_user)
  end

  def create
    @post = Post.find(params[:post_id])
    # 取得した記事がまだストックされていなければ
    unless @post.stocked?(current_user)
      # ログインしているユーザーを取得してparamsで渡された記事をストック
      @post.stock(current_user)
    end
    redirect_to request.referrer
  end

  def destroy
    @post = Stock.find(params[:id]).post
    # 取得した記事が既にストックされていれば
    if @post.stocked?(current_user)
      @post.unstock(current_user)
    end
    redirect_to request.referrer
  end
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/stocks/index.html.erb
	<% if @stock_posts.present? %>

		<div class="stock-page container">
		<div class="row stock-container-inner">
			<div class="stock-tag col-md-2 col-sm-3 col-xs-4">
				<div class="stock-tag-inner">
					<h4><strong>タグ</strong></h4>
					<% @stock_posts.each do |post| %>
						<% post.tags.each do |tag| %>
							<button class="stock-tag-name">
								<%= link_to tag.name, posts_path(tag_name: tag.name) %>
							</button>
						<% end %>
					<% end %>
				</div>
			</div>
			<% @stock_posts.each do |post| %>
				<div class="stock-index col-md-10 col-sm-9 col-xs-8">
					<div class="stock-post-articles row">
						<div class="stock-post-article col-md-1">
							<%= link_to user_path(post.user) do %>
								<%= attachment_image_tag post.user, :profile_image, :fill, 20, 20,fallback: "no_image.jpg", class: 'post-image' %>
							<% end %>
						</div>
						<div class="post-article col-md-11">
							<span class="stock-index-title"><%= link_to post.title, post_path(post) %></span>
							<span class="pull-right">
								<i class="far fa-comment"></i>
								<%= post.post_comments.count %>
							</span>
							<div class="stock-ul">
								<%= link_to post.user.name, user_path(post.user) %>さんが<%= time_ago_in_words(post.created_at) %>前に投稿
							</div>
							<div class="post-tag">
								<!-- タグ -->
								<% post.tags.each do |tag| %>
									<button class="post-button">
										<%= link_to tag.name, posts_path(tag_name: tag.name), class: "tag-btn" %>
									</button>
								<% end %>
								<!-- タグ -->
							</div>
						</div>
					</div>
				</div>
			<% end %>
		</div>
		</div>

	<% else %>
		<p>ストックはまだありません</p>
	<% end %>