config/routes.rb
Rails.application.routes.draw do
  root "posts#index"
  

  get "homes/about" => "homes#about"
  get "homes/privacy" => "homes#privacy"

  devise_for :users, controllers: {
    sessions: "devise/sessions",
    registrations: "devise/registrations",
  }

  post 'posts/confirm' => 'posts#confirm'
  resources :posts, only: [:index, :new, :create, :edit, :update, :show, :destroy] do
    resource :likes, only: [:create, :destroy]
    resource :post_comments, only: [:create]
  end
  delete "posts/:post_id/post_comments/:post_comment_id", to: "post_comments#destroy", as: :post_comment
  post "posts/:post_id/post_comments/:post_comment_id/thanks", to: "thanks#create", as: :thank
  delete "posts/:post_id/post_comments/:post_comment_id/thanks", to: "thanks#destroy"

  resource :tags, only: [:create, :destroy]
  resources :users, only: [:show, :edit, :update] do
    member do
      get :follow
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  post "/home/guest_sign_in" => "posts#new_guest"
  resources :relationships, only: [:create, :destroy]
  resources :stocks, only: [:index, :create, :destroy]

  # #例外処理
  # get '*not_found', to: 'application#routing_error'
  # post '*not_found', to: 'application#routing_error'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates_uniqueness_of :post_id, scope: :user_id
end

app/models/post.rb
class Post < ApplicationRecord
  acts_as_taggable
  belongs_to :user, optional: true
  has_many :post_comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  validates :title, presence: true, length: { maximum: 20 }
  validates :text, presence: true
  validates :emoji, presence: true
  validates :tag_list, presence: true

  has_many :stocks, dependent: :destroy
  has_many :stock_users, through: :stocks, source: :user

  enum status: { doing: 0, done: 1 }

  def liked_by?(user)
    likes.where(user_id: user.id).exists?
  end

  def stock(user)
    stocks.create(user_id: user.id)
  end

  def unstock(user)
    stocks.find_by(user_id: user.id).destroy
  end

  def stocked?(user)
    stock_users.include?(user)
  end
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :post
  belongs_to :user
  has_many :thanks, dependent: :destroy

  def thanked_by?(user)
    thanks.where(user_id: user.id).exists?
  end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/stock.rb
class Stock < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :user_id, presence: true
  validates :post_id, presence: true

  def self.get_stock_posts(user)
    where(user_id: user.id).map(&:post)
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
end

app/models/thank.rb
class Thank < ApplicationRecord
  belongs_to :user
  belongs_to :post_comment
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :thanks, dependent: :destroy

  attachment :profile_image

  validates :name, presence: true, length: { minimum: 2, maximum: 20 }
  validates :introduction, presence: true, length: { maximum: 500 }

  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed

  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :passive_relationships, source: :follower

  has_many :stocks, dependent: :destroy

  def follow(other_user)
    following << other_user
  end

  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end

  def privacy
  end
  
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_post

  def create
    like = @post.likes.new(user_id: current_user.id)
    like.save
    redirect_to request.referrer
  end

  def destroy
    like = current_user.likes.find_by(post_id: @post.id)
    like.destroy
    redirect_to request.referrer
  end

  private

  def set_post
    @post = Post.find(params[:post_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    @post = params[:post].present? ? Post.new(post_params) : Post.new
    @post.tag_list = params[:post].present? ? params[:post][:tag_list].split(',') : ""
    @post.emoji = params[:post].present? ? params[:post][:emoji] : "😄"
    @user = current_user
  end

  def confirm
    @post = Post.new(post_params)
  end

  def create
    @post = Post.new(post_params)
    @post.tag_list = params[:post][:tag_list]
    if @post.save
      flash[:notice] = "投稿が完了しました"
      redirect_to user_path(current_user)
    else
      render 'confirm'
    end
  end

  def index
    @all_ranking_posts = Post.find(Like.group(:post_id).order('count(post_id) desc').limit(10).pluck(:post_id))
    @contributors = PostComment.find(PostComment.group(:user_id).order('count(id) desc').limit(5).pluck(:id))

    @tags = Post.tag_counts_on(:tags).order('count desc')

    @q = Post.ransack(params[:q])
    if params[:tag_name]
      @posts = Post.tagged_with("#{params[:tag_name]}").includes(:tags).order(created_at: :desc).page(params[:page]).per(10)
    elsif params[:q]
      @posts = @q.result.order(created_at: :desc).page(params[:page]).per(10)
    else
      @posts = Post.all.order(created_at: :desc).page(params[:page]).per(10)
    end
    @user = current_user
  end

  def show
    @post = Post.find(params[:id])
    @post_comment = PostComment.new
    @post_comments = @post.post_comments.order(created_at: :desc)
  end

  def edit
    @post = Post.find(params[:id])
    if @post.user == current_user
      render 'edit'
    else
      redirect_back(fallback_location: posts_path, notice: "URLが有効ではありません")
    end
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      flash[:notice] = "更新しました"
      redirect_to post_path
    else
      render :edit
    end
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    flash[:notice] = "削除しました"
    redirect_to user_path(current_user)
  end

  def new_guest
    user = User.find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = 'guest'
      user.introduction = 'ゲストです。よろしくお願いします。'
    end
    sign_in user
    flash[:notice] = 'ゲストユーザーとしてログインしました。'
    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:user_id, :title, :text, :tag_list, :status, :emoji)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/thanks_helper.rb
module ThanksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<div class="outof-footer">
    <div class="container footer-inner">
        <footer>

 
                <%= link_to  "プライバシーポリシー", homes_privacy_path, class: "footer-list-1" %>
                <%= link_to  "notworryの使い方", homes_about_path, class: "footer-list-2" %>
                <div class="tree">
                    <%= image_tag'tree.png', class: "tree-image" %>
                </div>


                <div class="copy-right"><span>©notworry<span></div>

        </footer>
    </div>
</div>

app/views/layouts/_header.html.erb
<div class="outof-header">
<div class="container header-container">
<header>
  <div class="header-left">
    <div class="top-imagephoto">
    <% if user_signed_in? %>
      <%= link_to posts_path do %>
            <%= image_tag'notworry.png', class: "original-image" %>
      <% end %>
    <% else %>
      <%= link_to root_path do %>
          <%= image_tag'notworry.png', class: "original-image" %>
      <% end %>
    <% end %>
    </div>
    <ul class="header-list pull-right">
    <% if user_signed_in? %>
      
      <li class="text-right header-element">
            <%= link_to stocks_path do %>
              <i class="fab fa-get-pocket"></i>
            <% end %>
        </li>
        <li class="text-right header-element">
            <%= link_to new_post_path do %>
              <i class="fas fa-pen"></i>
            <% end %>
        </li>
        <li class="text-right header-element">
            <%= link_to user_path(current_user) do %>
              <i class="fas fa-user"></i>
            <% end %>
        </li>
        <li class="text-right header-element">
          <%= link_to destroy_user_session_path, method: :delete do %>
            <i class="fas fa-sign-out-alt"></i> 
          <% end %>
        </li>
    <% else %>
      <li class="text-right header-element"><%= link_to "新規登録", new_user_registration_path %></li>
      <li class="text-right header-element"><%= link_to "ログイン", new_user_session_path %></li>
    <% end %>
    </ul>

  </div>
</header>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>notworry | 20代のキャリア悩みを解決する</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
    <%= favicon_link_tag('favicon.ico') %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.9.0/css/all.css"> <!-- font awesome-->
    <link href="https://fonts.googleapis.com/css2?family=Lato:wght@400;700&family=Noto+Sans+JP:wght@400;700&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
  <div class="wrap">
    <%= render 'layouts/header' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </div>
  </body>
</html>

app/views/searches/_search.html.erb
<%= search_form_for @q do |f| %>
    <%= f.label :text_cont, "キーワード検索" %>
    <%= f.search_field :text_cont %>
    <%= f.submit "検索" %>
<% end %>